
networks:
  nfttest-net:
    external: false


services:
  peer1:
    build:
      context: .
    volumes:
      - ./src/nft-helper:/etc/init.d/nft-helper
      - ./src/nft-helper.sh:/usr/local/bin/nft-helper.sh
      - ./src/nft-helper.daily.sh:/etc/periodic/daily/nft-helper.daily.sh

      - ./test/nft_settings.sh:/root/nft_settings.sh
      - ./test/test_tbl-test_out-testset.list:/etc/nftlists/available/test_tbl-test_out-testset.list

      - ./lists:/etc/netlists/
      - ./examples:/usr/share/nftlist/

    networks:
      - nfttest-net

    cap_add: ['SYS_ADMIN']
    privileged: true

  peer2:
    build:
      context: .
    volumes:
      - ./src/nft-helper:/etc/init.d/nft-helper
      - ./src/nft-helper.sh:/usr/local/bin/nft-helper.sh
      - ./src/nft-helper.daily.sh:/etc/periodic/daily/nft-helper.daily.sh

      - ./test/nft_settings.sh:/root/nft_settings.sh
      - ./test/test_tbl-test_out-testset.list:/etc/nftlists/available/test_tbl-test_out-testset.list

      - ./lists:/etc/netlists/
      - ./examples:/usr/share/nftlist/

    networks:
      - nfttest-net

    cap_add: ['SYS_ADMIN']
    privileged: true

